### ISSUE TITLE
Download if there is a video instead of image 

### ISSUE THREAD

**Issue by xxczaki** [xxczaki/nasa-cli#20]
Currently, where there is a video instead of an image, nasa-cli fails. We should instead download this video :)

**Comment by chrux** [comment]
Hey, do you have an example to test this?

**Comment by xxczaki** [comment]
@chrux for example `nasa --date 171220` returns `✖ Something went wrong :( Try again later!`, because Picture of the day from 20 December 2017 is a video (https://apod.nasa.gov/apod/ap171220.html).

**Comment by xxczaki** [comment]
@chrux note, that we do not need to download the video, instead we can:
- return a link to that video
- make a custom error saying that the APOD from this day is a video
